[package]
name = "t-rex"
version = "0.7.8-dev"
description = "vector tile server"
repository = "https://github.com/pka/t-rex"
readme = "README.md"
license = "MIT"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]

[[bin]]
name = "t_rex"

[dependencies]
t-rex-core = { path = "t-rex-core" }
t-rex-webserver = { path = "t-rex-webserver" }
t-rex-gdal = { path = "t-rex-gdal" }
clap = "*"
log = "*"
env_logger = "*"
time = "*"

[workspace]
